DROP DATABASE IF EXISTS gopher;
CREATE DATABASE gopher;

\c gopher

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE lists (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  date timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE lists_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES lists ON DELETE CASCADE,
  list_id integer NOT NULL REFERENCES lists ON DELETE CASCADE
);

CREATE TABLE list_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id integer NOT NULL REFERENCES lists ON DELETE CASCADE,
  name text NOT NULL,
  price numeric,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE list_items_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_item_id integer NOT NULL REFERENCES list_items ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE list_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text CONSTRAINT check_list_event_type CHECK (event_type IN ('add', 'delete', 'modify')),
  start_id integer REFERENCES list_items ON DELETE CASCADE,
  end_id integer REFERENCES list_items ON DELETE CASCADE,
  date timestamp with time zone DEFAULT current_timestamp
);
